#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 12 09:07:07 2020

@author: slomogangsta
"""

t = int(input())
for _ in range(t):
    count=0
    num = int(input())
    arr = list(map(int,str(num)))
    for i in arr:
        if(num%i==0):
            count=count+0
    print(count)