#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 27 20:25:29 2020

@author: slomogangsta
"""

n,k = map(int,input().split())
arr = list(map(int,input().split()))
'''    for _ in range(k):
    temp = arr[0]
    for i in range(len(arr)-1):
        arr[i]=arr[i+1]
    arr[-1]=temp
    print(arr)
print(arr)'''

temp = [0 for _ in range(n)]
for i in range(n):
    temp[(i+(n-k))%n]=arr[i]
print(*temp)