#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar 27 18:54:19 2020

@author: slomogangsta
"""
'''arr=sorted(arr)
print(arr)
temp=arr[0]
c=0
for i in range(0,len(arr),2):
    x=arr[i]
    if(i+1<len(arr)):
        temp=arr[i+1]
    else:
        temp=-1
    print(x,temp,sep=' ')
    if(x==temp):
        c=c+1
        print("Count: ",c)
print("final count: ",c)'''

n = int(input())
arr = list(map(int, input().rstrip().split()))
c=0
temp=[0 for _ in range(len(arr))]
for i in range(len(arr)):
    if(temp.count(arr[i])==0):
        temp.insert(i,arr[i])
    else:
        c=c+1
        temp.remove(arr[i])
print(c)